### PR TITLE
NISP 2083 - Removing dependency on breadcrumb icon from GDS servers

### PR DESCRIPTION
**Pull request by roundrobin99**
- Moved the breadcrumb arrow icon into our service
- Added styling in our nisp.scss for the breadcrumb arrow icon
- Refactored styling for #global-breadcrumb
- Revised service url for existing image path at top of nisp.scss
- I've also removed redundant styles that are not used any more such as `cope-table` and `icon-x`

### CODE REVIEW

**Comment by prashantchoudhari** [comment]
@InduTest  @swaistle  - Please test and confirm

**Comment by InduTest** [comment]
@roundrobin99  Please let us know once ur done

**Comment by roundrobin99** [comment]
This is now complete @InduTest . Ready for testing.

**Comment by dspork** [comment]
Merge when satisfied

**Comment by InduTest** [comment]
Tested different devices and me and @swaistle  are fine with this

**Pull request merged**
