### PR TITLE
NISP-1612 Fixing bug with iPhone 6

### PR DESCRIPTION
**Pull request by roundrobin99**
Increased width to 780px since this is the breakpoint where the tabs are nominal

### CODE REVIEW

**Comment by prashantchoudhari** [comment]
@InduTest  - Please can you test it and confirm this is fine? We can merge it then.

**Comment by InduTest** [comment]
@prashantchoudhari yes will do and confirm. But once deployed into QA will have to test on physical device as well.

**Comment by roundrobin99** [comment]
@prashantchoudhari, and @InduTest - Kiran said he can test on his mobile.

**Comment by dspork** [comment]
Does this have implications for other devices that are not iPhone 6?

**Comment by InduTest** [comment]
Have retested few devices and looks fine

**Comment by roundrobin99** [comment]
@dspork I have tested on other devices (and desktop browsers as well) and it works well across the spectrum.

**Pull request merged**
