### PR TITLE
Nisp 1578 Fixing Sass warnings

### PR DESCRIPTION
**Pull request by roundrobin99**
1. Added configuration settings in Gruntfile.js
2. Added linter configuration list (in root) : .scss-lint.yaml
3. Added option to output to a file in the /logs/reports/scss-lint-report.xml file (an XML Beautifier is your friend!)
4. Fixed more than 90% of warnings

The "!important" have to stay I am afraid, because there is no other way.
As for the IDs, they have to stay.

### CODE REVIEW

**Comment by andrewgee** [comment]
@roundrobin99 Might be worth talking to frontend people about taking the `!important` off of the h2 in assets-frontend?
Also, what was the problem with the IDs that you say have to stay?

**Comment by roundrobin99** [comment]
@andrewgee Good idea about talking to the frontend team, but I guess they had a reason for using them.

No problem really, I just don't see an issue not using IDs for unique elements. They are there for a reason. 
As you will remember, I did mention that we should be using IDs sparingly, but not to avoid them completely. There is a lot of controversy around this. Here is a link that I agree with : 

http://csswizardry.com/2011/09/when-using-ids-can-be-a-pain-in-the-class/

**Comment by andrewgee** [comment]
@roundrobin99 Cool, interesting article.

**Comment by roundrobin99** [comment]
Thanks @andrewgee

**Pull request merged**
