### PR TITLE
NISP-1656: Corrected heading styles throughout service

### PR DESCRIPTION
**Pull request by andrewgee**

### CODE REVIEW

**Comment by roundrobin99** [comment]
Why are all the styles removed ?

**Comment by andrewgee** [comment]
@roundrobin99 They are now all covered by: https://github.com/hmrc/nisp-frontend/blob/NISP-1656/app/uk/gov/hmrc/nisp/assets/sass/nisp.scss#L49

**Comment by andrewgee** [comment]
Unsure why some of the travis checks have failed. Tested locally and working.

**Comment by roundrobin99** [comment]
@andrewgee  Something to do with beta feedback form not responding ?

**Pull request merged**
