### PR TITLE
NISP-1602 removing NI Record Feedback

### PR DESCRIPTION
**Pull request by roundrobin99**
Removed HTML, Controller, Event and Model related to NI record feedback.

### CODE REVIEW

**Comment by andrewgee** [comment]
Is the removal of nisp.nifeedback.comments.feedback.* missing?

**Comment by andrewgee** [comment]
The tests also need updating, as they currently don't run

**Comment by roundrobin99** [comment]
@andrewgee  What do you mean by missing ?

**Comment by andrewgee** [comment]
@roundrobin99 There are a bunch of nisp.nifeedback.comments.feedback.* messages still present in the messages file. Do these need removing?

**Comment by roundrobin99** [comment]
@andrewgee Yeah. I got confused with the css! Beeing a looong day.

**Pull request merged**
