### PR TITLE
Nisp 1915 - Added question for research with email address

### PR DESCRIPTION
**Pull request by roundrobin99**
- Uses Jquery to display/hide depending on the answer
- script only loads if the questionnaire component is loaded
- bumped questionnaire version to 6

### CODE REVIEW

**Comment by prashantchoudhari** [comment]
Please do not merge, as Dimitrios is working on improving it.

**Comment by roundrobin99** [comment]
Working on validating the email address

**Comment by dspork** [comment]
I think the play framework has a thing for that see what happens if you change `text -> email` in `QuestionnaireForm``https://playframework.com/documentation/2.0/api/scala/play/api/data/Forms$.html

**Comment by roundrobin99** [comment]
Thanks @dspork

**Comment by dspork** [comment]
Do you think we need some logic around the sending of the event?
If the user clicks "Yes" inputs their address and then clicks "No" and clicks submit. The service will still store their email address.
Should we add some busines logic to stop sending the email address if `research != 0`?

**Comment by dspork** [comment]
Also should we use the `emailWithDomain` validation from play-ui as this ensures a domain (e.g. .com) whereas the Play framework one does not?

**Comment by roundrobin99** [comment]
We can remove the email from the form, if user clicks 'No' after typing an email address.

**Comment by roundrobin99** [comment]
I have added some validation logic so when user clicks NO after supplying an email address, the email address is removed.

**Comment by roundrobin99** [comment]
in regards to `emailDomain`,I have checked the form and unless you provide a full email address (with .com for example), the form is not progressing so I don't see any need for it.

**Comment by roundrobin99** [comment]
I also need to look at the GDS styling for conditionally revealing content, because at the moment our style doesn't match that of GDS. I will have a look with other services and see what we can do.

**Comment by roundrobin99** [comment]
This PR is now ready for full release, pending testing from @InduTest

**Comment by roundrobin99** [comment]
Do not merge this yet. We need to fix the style of error message in the email field. IT should be displayed below the field label, like is shown here > http://govuk-elements.herokuapp.com/errors/#example-full-name

**Comment by roundrobin99** [comment]
The email style is now fixed.This is ready for testing and merging.

**Pull request merged**
