### PR TITLE
NISP-2343 : Added Exclusion unit tests 

### PR DESCRIPTION
**Pull request by nehakannaujia**
NISP-2343 : Added unit tests for Exclusions and resolved conflict with base branch

### CODE REVIEW

**Comment by Shaju-11** [comment]
I believe it is enough test coverage as me and @nehakannaujia went through it together @dspork

**Comment by dspork** [comment]
@nehakannaujia I've made some conflicting changes from another branch would you be able to resolve the conflicts in hear? :bowing_man:

**Comment by nehakannaujia** [comment]
done :-)

**Comment by nehakannaujia** [comment]
@dspork:  Resolved conflict. Please review :-)

**Pull request merged**
